language: perl
perl:
  - system
os:
  - linux
  - osx
env:
  - PVER=5.28.0 ARGS='--thread -Accflags="-fsanitize=address -g -O2" -Aldflags="-fsanitize=address -g -O2"'
  - PVER=5.28.0 ARGS='--debug --thread -Accflags="-fsanitize=address -g -O2" -Aldflags="-fsanitize=address -g -O2"'
  - PVER=5.28.0 ARGS='--thread -Accflags="-fsanitize=address -g -O2" -Aldflags="-fsanitize=address -g -O2"'
sudo: false
before_install:
  - \curl -L https://install.perlbrew.pl | bash
  - source ~/perl5/perlbrew/etc/bashrc
  - perlbrew install $ARGS $PVER
  - perlbrew switch $PVER
  - perl -V
script:
  - perl Makefile.PL
  - make
  - prove -b -l -j$(test-jobs) $(test-files)   # parallel testing
