language: perl
perl:
  - system
os:
  - linux
  - osx
env:
  - PVER=5.28
  - PVER=5.4
  - PVER=5.28 ARGS=--debug
  - PVER=5.4 ARGS=--debug
sudo: false
before_install:
  - \curl -L https://install.perlbrew.pl | bash
  - source ~/perl5/perlbrew/etc/bashrc
  - perlbrew install $PVER
  - perlbrew switch $PVER
  - perl -V
script:
  - perl Makefile.PL
  - make
  - prove -b -l -j$(test-jobs) $(test-files)   # parallel testing
