language: shell
os:
  - linux
  - osx
  - windows
matrix:
    exclude:
    - os: windows
      env: ASAN_OPTIONS='halt_on_error=0:detect_leaks=0' PVER=5.28.0 ARGS='--debug --thread -Accflags=-fsanitize=address -Accflags=-g -Accflags=-O2 -Aldflags=-fsanitize=address -Aldflags=-g -Aldflags=-O2'
    - os: windows
      env: ASAN_OPTIONS='halt_on_error=0:detect_leaks=0' PVER=5.28.0 ARGS='--debug -Accflags=-fsanitize=address -Accflags=-g -Accflags=-O2 -Aldflags=-fsanitize=address -Aldflags=-g -Aldflags=-O2'
    - os: windows
      env: PVER=5.28.0 ARGS='-Aldflags=-g -Aldflags=-O2'
env:
  - ASAN_OPTIONS='halt_on_error=0:detect_leaks=0' PVER=5.28.0 ARGS='--debug --thread -Accflags=-fsanitize=address -Accflags=-g -Accflags=-O2 -Aldflags=-fsanitize=address -Aldflags=-g -Aldflags=-O2'
  - ASAN_OPTIONS='halt_on_error=0:detect_leaks=0' PVER=5.28.0 ARGS='--debug -Accflags=-fsanitize=address -Accflags=-g -Accflags=-O2 -Aldflags=-fsanitize=address -Aldflags=-g -Aldflags=-O2'
  - PVER=5.28.0 ARGS='-Aldflags=-g -Aldflags=-O2'
  - PVER=5.28.0 ARGS='--thread --debug -Aldflags=-g -Aldflags=-O2'
    #- PVER=5.28.0 ARGS='--debug --thread -Accflags="-fsanitize=address -g -O2" -Aldflags="-fsanitize=address -g -O2"'
    #- PVER=5.28.0 ARGS='--thread -Accflags="-fsanitize=address -g -O2" -Aldflags="-fsanitize=address -g -O2"'
addons:
  homebrew:
    packages:
    - cpanminus

before_install:
  - "if [[ \"$TRAVIS_OS_NAME\" != windows ]]; then curl -L https://install.perlbrew.pl | bash; fi"
  - "if [[ \"$TRAVIS_OS_NAME\" != windows ]]; then source ~/perl5/perlbrew/etc/bashrc; fi"
  - "if [[ \"$TRAVIS_OS_NAME\" != windows ]]; then ( sleep 10; tail -f $HOME/perl5/perlbrew/build.*.log ) & else true; fi"
  - "if [[ \"$TRAVIS_OS_NAME\" != windows ]]; then perlbrew install -j 4 --notest --noman $ARGS $PVER || cat $HOME/perl5/perlbrew/build.*.log; fi"
  - "if [[ \"$TRAVIS_OS_NAME\" != windows ]]; then perlbrew switch $PVER; fi"
  - "if [[ \"$TRAVIS_OS_NAME\" == windows ]]; then choco install strawberryperl; fi"
  - perl -V
  - echo yes | cpan ExtUtils::MakeMaker
script:
  - perl Makefile.PL verbose
  - if [ "$TRAVIS_OS_NAME" != 'windows' ]; then make=make; else make=cmake
  - $make
  - export ASAN_OPTIONS=detect_leaks=0
  - $make test TEST_VERBOSE=1
