language: "perl"
os:
  - linux
  - osx
perl:
  - "5.30-shrplib"
  - "5.26-shrplib"
  - "5.24-shrplib"
  - "5.22-shrplib"
  - "5.20-shrplib"
  - "5.18-shrplib"
  - "5.30"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
