language: perl
perl:
  - system
os:
  - linux
  - osx
env:
  - ASAN_OPTIONS='halt_on_error=0:detect_leaks=0' PVER=5.28.0 ARGS='--thread -Accflags=-fsanitize=address -Accflags=-g -Accflags=-O2 -Aldflags=-fsanitize=address -Aldflags=-g -Aldflags=-O2'
    #- PVER=5.28.0 ARGS='--debug --thread -Accflags="-fsanitize=address -g -O2" -Aldflags="-fsanitize=address -g -O2"'
    #- PVER=5.28.0 ARGS='--thread -Accflags="-fsanitize=address -g -O2" -Aldflags="-fsanitize=address -g -O2"'
sudo: false
before_install:
  - \curl -L https://install.perlbrew.pl | bash
  - source ~/perl5/perlbrew/etc/bashrc
  - ( sleep 10; tail -f /home/travis/perl5/perlbrew/build.*.log ) &
  - perlbrew install -j 4 --notest --noman $ARGS $PVER || cat /home/travis/perl5/perlbrew/build.*.log
  - perlbrew switch $PVER
  - perl -V
script:
  - perl Makefile.PL
  - make
  - export ASAN_OPTIONS=detect_leaks=0
  - prove -b -l -r t
